[package]
name = "helios"
version = "1.0.0"
edition = "2021"
description = "Helios - A blazing-fast terminal API client"

[[bin]]
name = "helios"
path = "src/main.rs"

[dependencies]
# CLI
clap = { version = "4.5", features = ["derive"] }

# Async runtime & HTTP
tokio = { version = "1.37", features = ["full"] }
reqwest = { version = "0.12", features = ["json", "multipart"] }

# TUI
ratatui = "0.26"
crossterm = "0.27"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }

# Error handling
anyhow = "1.0"

# System directories
directories = "5.0"

# Utility
uuid = { version = "1.8", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
serde_urlencoded = "0.7"
serde_yaml = "0.9"
tempfile = "3.10"

# Vault (密钥保险箱)
aes-gcm = "0.10"
rand = "0.8"
pbkdf2 = { version = "0.12", features = ["simple"] }
sha2 = "0.10"
hmac = "0.12"
base64 = "0.22"

[target.'cfg(target_os = "macos")'.dependencies]
keyring = "2"
